import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from 'next';
import { Kodchasan, Poppins } from 'next/font/google';
import '../styles/globals.css';


const kodchasan = Kodchasan({
  variable: '--font-kodchasan',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Saas Finance',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${kodchasan.variable} antialiased`}>
        {children}
        <Toaster
          toastOptions={{
            className: 'bg-[#251930] text-[#f9f8fa]',
            duration: 3000,
            style: {
              background: '#251930',
              color: '#f9f8fa',
            },
          }}
          position="top-center"
          />
      </body>
    </html>
  );
}
